---
- name: install elasticsearch logstash and kibana
  hosts: elasticsearch
  gather_facts: true
  become: true
  tasks:
    - name: Reset elastic password
      when: inventory_hostname == 'node1'
      ansible.builtin.command:
        cmd: "{{ es_bin_dir }}/elasticsearch-reset-password -u elastic -b -i"
        stdin: "{{ elastic_password }}\n{{ elastic_password }}"
      register: cli_output_elastic
      changed_when: true

    - name: Show CLI execution results
      when: inventory_hostname == 'node1'
      ansible.builtin.debug:
        var: cli_output_elastic.stdout_lines

    - name: Reset kibana_system password
      when: inventory_hostname == 'node1'
      ansible.builtin.command:
        cmd: "{{ es_bin_dir }}/elasticsearch-reset-password -u kibana_system -b -i"
        stdin: "{{ kibana_system_password }}\n{{ kibana_system_password }}"
      register: cli_output
      changed_when: true

    - name: Show CLI execution results
      when: inventory_hostname == 'node1'
      ansible.builtin.debug:
        var: cli_output.stdout_lines
