---
- name: install elasticsearch logstash and kibana
  hosts: elasticsearch
  gather_facts: true
  become: true
  tasks:
    - name: Deploy Elasticsearch configuration
      register: config_file
      ansible.builtin.template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: '0660'

    - name: Enable and start Elasticsearch service
      when: config_file is changed
      ansible.builtin.systemd_service:
        name: elasticsearch
        state: restarted
        enabled: yes
