---
- name: install elasticsearch logstash and kibana
  hosts: elasticsearch
  gather_facts: true
  become: true
  tasks:
    - name: Install Elasticsearch
      ansible.builtin.dnf:
        name: "elasticsearch"
        state: present
        enablerepo: elasticsearch

    - name: Get current timestamp
      setup:
        filter: ansible_date_time

    - name: Backup existing certificates by renaming them
      ansible.builtin.shell: |
        if [ -f "{{ item }}" ]; then
          mv "{{ item }}" "{{ item }}_{{ ansible_date_time.iso8601_basic_short }}"
        fi
      loop:
        - /usr/share/elasticsearch/elastic-stack-ca.p12
        - /usr/share/elasticsearch/elastic-certificates.p12
      register: rename_result
      changed_when: "rename_result.rc == 0"

    - name: Generate Certificate Authority
      when: inventory_hostname == 'node1'
      ansible.builtin.command:
        cmd: "{{ es_bin_dir }}/elasticsearch-certutil ca --pass '' --out elastic-stack-ca.p12 --silent"
      changed_when: true

    - name: Generate TLS Certificate
      when: inventory_hostname == 'node1'
      ansible.builtin.command:
        cmd: "{{ es_bin_dir }}/elasticsearch-certutil cert --ca elastic-stack-ca.p12 --pass '' --ca-pass '' --out elastic-certificates.p12 --silent"
      changed_when: true

    - name: Fetch CA certificate
      when: inventory_hostname == 'node1'
      fetch:
        src: "/usr/share/elasticsearch/elastic-stack-ca.p12"
        dest: /tmp/elastic-stack-ca.p12
        flat: true

    - name: Fetch node certificate
      when: inventory_hostname == 'node1'
      fetch:
        src: "/usr/share/elasticsearch/elastic-certificates.p12"
        dest: /tmp/elastic-certificates.p12
        flat: true

    - name: Copy CA certificate to all elasticsearch nodes
      ansible.builtin.copy:
        src: /tmp/elastic-stack-ca.p12
        dest: /etc/elasticsearch/certs/elastic-stack-ca.p12
        owner: root
        group: elasticsearch
        mode: '0660'

    - name: Copy node certificate to all elasticsearch nodes
      ansible.builtin.copy:
        src: /tmp/elastic-certificates.p12
        dest: /etc/elasticsearch/certs/elastic-certificates.p12
        owner: root
        group: elasticsearch
        mode: '0660'
