---
- name: install elasticsearch logstash and kibana
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install Elasticsearch
      when: "'elasticsearch' in group_names"
      ansible.builtin.dnf:
        name: "elasticsearch"
        state: present
        enablerepo: elasticsearch

    - name: Enable and start Elasticsearch service
      when: "'elasticsearch' in group_names"
      ansible.builtin.service:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Install Kibana
      when: "'kibana' in group_names"
      ansible.builtin.yum:
        name: kibana
        state: present

    - name: Configure Kibana to listen on all interfaces
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#?server\.host:'
        line: 'server.host: "0.0.0.0"'
        state: present

    - name: Start and enable Kibana service
      when: "'kibana' in group_names"
      ansible.builtin.service:
        name: kibana
        state: started
        enabled: yes

    - name: Install Logstash and Beats
      ansible.builtin.dnf:
        name:
          - logstash
          - filebeat
          - metricbeat
        state: present
        update_cache: true
      when: "'kibana' in group_names"

    - name: Install Logstash and Beats on Kibana group hosts
      ansible.builtin.dnf:
        name:
          - logstash
          - filebeat
          - metricbeat
        state: present
        update_cache: true
      when: "'kibana' in group_names"

    - name: Restart logstash
      when: "'kibana' in group_names"
      ansible.builtin.systemd_service:
        name: logstash
        state: restarted
        enabled: true

    - name: Restart filebeat
      when: "'kibana' in group_names"
      ansible.builtin.systemd_service:
        name: filebeat
        state: restarted
        enabled: true

    - name: Restart metricbeat
      when: "'kibana' in group_names"
      ansible.builtin.systemd_service:
        name: metricbeat
        state: restarted
        enabled: true
